#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

usage() {
  echo "$0 <alias>" >&2
  exit 1
}

# shellcheck source=/dev/null
source "$ROOT_DIR/utils/source.sh"
source_modules \
  utils/host.sh \
  utils/profile.sh \
  utils/validate.sh

main() {
  [ "$#" -eq 1 ] || usage
  validate_names "$1"
  profile_prepare
  if ! host_exists "$1"; then
    exit 1
  fi
  host_remove "$1"
  exec "$ROOT_DIR/status"
}

main "$@"
