#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

usage() {
  echo "$0" >&2
  exit 1
}

# shellcheck source=/dev/null
source "$ROOT_DIR/utils/source.sh"
source_modules \
  utils/host.sh \
  utils/profile.sh \
  utils/table.sh

status_add_host_row() {
  table_add_row "$1" "$2" "${4:--}"
}

main() {
  [ "$#" -eq 0 ] || usage
  profile_prepare
  table_reset
  table_set_headers ALIAS USER SSH
  host_each status_add_host_row
  table_print
}

main "$@"
