profile_prepare() {
  MARIONETTE_HOME=${MARIONETTE_HOME:-"$HOME/.config/marionette"}
  MARIONETTE_PROFILES_DIR=$MARIONETTE_HOME/profiles
  MARIONETTE_STATE_DIR=$MARIONETTE_HOME/state
  MARIONETTE_GENERATED_CONFIG_FILE=$MARIONETTE_STATE_DIR/ssh_config
  MARIONETTE_HOSTS_FILE=$MARIONETTE_PROFILES_DIR/default/hosts
  MARIONETTE_KNOWN_HOSTS_FILE=$MARIONETTE_PROFILES_DIR/default/known_hosts
  mkdir -p "$MARIONETTE_PROFILES_DIR" "$MARIONETTE_STATE_DIR"
  mkdir -p "$MARIONETTE_PROFILES_DIR/default"
  [ -f "$MARIONETTE_HOSTS_FILE" ] || : >"$MARIONETTE_HOSTS_FILE"
  [ -f "$MARIONETTE_KNOWN_HOSTS_FILE" ] || : >"$MARIONETTE_KNOWN_HOSTS_FILE"
}
