profile_prepare() {
  STRAND_HOME=${STRAND_HOME:-"$HOME/.config/strand"}
  STRAND_PROFILES_DIR=$STRAND_HOME/profiles
  STRAND_STATE_DIR=$STRAND_HOME/state
  STRAND_GENERATED_CONFIG_FILE=$STRAND_STATE_DIR/ssh_config
  STRAND_HOSTS_FILE=$STRAND_PROFILES_DIR/default/hosts
  STRAND_KNOWN_HOSTS_FILE=$STRAND_PROFILES_DIR/default/known_hosts
  mkdir -p "$STRAND_PROFILES_DIR" "$STRAND_STATE_DIR"
  mkdir -p "$STRAND_PROFILES_DIR/default"
  [ -f "$STRAND_HOSTS_FILE" ] || : >"$STRAND_HOSTS_FILE"
  [ -f "$STRAND_KNOWN_HOSTS_FILE" ] || : >"$STRAND_KNOWN_HOSTS_FILE"
}
